### PR TITLE
S3 Default Region Fix

### PR DESCRIPTION
**Pull request by rflaperuta**
When creating a bucket the sdk throws an error for the LocationConstraint = 'us-east-1', according to research on the error. For these region the LocationConstraint shouldn't be used.

### CODE REVIEW

**Comment by jfbenckhuijsen** [comment]
I can look into this pull request, however main issue is that the initial setup doesn't work. I forked this from the original code, only to find the base image Lambda runs on does not include the required packages to compile local binaries. Haven't been able to look into this since.

**Comment by rflaperuta** [comment]
I'd be glad if you do. Currently, the other repos seem abandoned, yours is the most complete.

Thanks in advance.

**Comment by jfbenckhuijsen** [comment]
Hi, I've checked the code and it contains a lot of changes to the formatting of the code, making this request a bit problematic to merge, as I'd like to keep the formatting consistent with the old formatting. Are you able to filter these changes out?

**Comment by rflaperuta** [comment]
I'll try to maintain formatting. My guess it is better to close this. And look into a new commit.

**Pull request closed without merging**
